name: "Hello Actions"
description: "Greet someone"
author "daniel@medina.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
    
runs:
  using: "docker"
  image: "Dockerfile
  
branding:
  icon: "mic"
  color: "purple"
